local ADDON = ...
local TYPE = "border"
local PATH = "Interface\\AddOns\\"..ADDON.."\\"..TYPE.."\\"
local M = LibStub("LibSharedMedia-3.0")

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED

M:Register(TYPE, "Glass",       PATH.."Glass")
M:Register(TYPE, "Roth Mono",   PATH.."Roth_Mono")
M:Register(TYPE, "Roth Square", PATH.."Roth_Square")
M:Register(TYPE, "Glow",        PATH.."Glow")
M:Register(TYPE, "Vol",         PATH.."Vol")
