#!/usr/bin/env bash

MEDIA_TYPES=( "background" "border" "font" "sound" "statusbar" )

function make_listfile {
	TYPE="$1"
	OUTFILE="${TYPE}.lua"

	echo "-- THIS FILE IS AUTOMATICALLY GENERATED" > "$OUTFILE"
	echo "local ADDON = ..." >> "$OUTFILE"
	echo "local TYPE = '${TYPE}'" >> "$OUTFILE"
	echo "local PATH = 'Interface\\\AddOns\\\' .. ${ADDON} .. '\\\' .. ${TYPE} .. \\\'" >> "$OUTFILE"
	echo "local M = LibStub('LibSharedMedia-3.0')" >> "$OUTFILE"

	for FILE in "${TYPE}"/*.* ; do
		# Get filename without path
		FILE=$( basename "$FILE" )
		# Convert filename to media title
		NAME="${FILE%.*}" # remove extension
		NAME="${NAME^}" # uppercase first character
		NAME=$( echo "$NAME" | sed -r 's/[-_](.)/ \U\1/g' \
			| sed -r 's/([a-z0-9])([A-Z])/\1 \2/g' \
			| sed -r 's/([a-z])([0-9])/\1 \2/g' \
			| sed -r 's/([A-Z][A-Z])([A-Z][a-z])/\1 \2/g' )
		if [ "$TYPE" == "font" ] ; then
			NAME=$( echo "$NAME" | sed 's/ Regular$//' )
		fi
		# Add to file
		echo "M:Register(TYPE, '${NAME}', PATH .. '${FILE}')" >> "$OUTFILE"
	done
}

NEWDIRS=""
for TYPE in "${MEDIA_TYPES[@]}" ; do
	if [ -d "$TYPE" ]; then
		make_listfile "$TYPE"
		echo "Imported ${TYPE} media files."
	else
		mkdir "$TYPE"
		NEWDIRS="$NEWDIRS, $TYPE"
	fi
done

if [ ! -z "$NEWDIRS" ]; then
	NEWDIRS=$( echo "$NEWDIRS" | cut -c 3- )
	echo "Created new folders for media types: $NEWDIRS"
	echo "Place your media files in the appropriate folders and run this script again."
fi
