#!/usr/bin/env bash

ADDON_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd )
ADDON_NAME=$( basename "$ADDON_PATH" )

LISTFILE="${ADDON_PATH}/media.lua"
MEDIA_TYPES=( "background" "border" "font" "sound" "statusbar" )

TOCFILE="${ADDON_PATH}/${ADDON_NAME}.toc"

if [ ! -f "$TOCFILE" ]; then
	echo -n "Enter current WoW interface version number: "
	read INTERFACE_VERSION
	if echo "$INTERFACE_VERSION" | grep -q -E '^[1-9][0-9][0-9][0-9][0-9]+$' ; then
		echo "## Interface: ${INTERFACE_VERSION}" > "$TOCFILE"
		echo "media.lua" >> "$TOCFILE"
		echo "Created TOC file"
	else
		echo "INVALID $INTERFACE_VERSION"
		exit 1
	fi
fi

function add_media {
	TYPE="$1"
	for FILE in "${TYPE}"/* ; do
		if [ -f "$FILE" ]; then
			# Get filename without path
			FILE=$( basename "$FILE" )
			# Convert filename to media title
			NAME="${FILE%.*}" # remove extension
			NAME="${NAME^}" # uppercase first character
			NAME=$( echo "$NAME" | sed -r 's/[-_](.)/ \U\1/g' \
				| sed -r 's/([a-z0-9])([A-Z])/\1 \2/g' \
				| sed -r 's/([a-z])([0-9])/\1 \2/g' \
				| sed -r 's/([A-Z][A-Z])([A-Z][a-z])/\1 \2/g' )
			if [ "$TYPE" == "font" ] ; then
				NAME=$( echo "$NAME" | sed 's/ Regular$//' )
			fi
			# Add to file
			FILEPATH="Interface\\\\AddOns\\\\${ADDON_NAME}\\\\${TYPE}\\\\${FILE}"
			echo "M:Register('${TYPE}', '${NAME}', '${FILEPATH}')" >> "$LISTFILE"
		fi
	done
}

echo "-- THIS FILE IS AUTOMATICALLY GENERATED" > "$LISTFILE"
echo "local f = CreateFrame('Frame')" >> "$LISTFILE"
echo "f:RegisterEvent('ADDON_LOADED')" >> "$LISTFILE"
echo "f:SetScript('OnEvent', function(f, e)" >> "$LISTFILE"
echo "local M = LibStub and LibStub('LibSharedMedia-3.0', true)" >> "$LISTFILE"
echo "if not M then return end" >> "$LISTFILE"
echo "f:UnregisterEvent(e)" >> "$LISTFILE"

NEWDIRS=""
for TYPE in "${MEDIA_TYPES[@]}" ; do
	if [ -d "$TYPE" ]; then
		if [ -z "$(ls -A "$TYPE")" ]; then
			rm -r "$TYPE"
			echo "Removed empty folder: $TYPE"
		else
			add_media "$TYPE"
			echo "Imported media for type: $TYPE"
		fi
	else
		mkdir "$TYPE"
		NEWDIRS="$NEWDIRS $TYPE"
	fi
done

echo "end)" >> "$LISTFILE"

if [ ! -z "$NEWDIRS" ]; then
	echo "Created new folders for media types:$NEWDIRS"
	echo "Place your media files in the appropriate folders and run this script again."
fi
