local ADDON = ...
local TYPE = "statusbar"
local PATH = "Interface\\AddOns\\"..ADDON.."\\"..TYPE.."\\"
local M = LibStub("LibSharedMedia-3.0")

--M:Register(TYPE, "Armory", PATH.."Armory")
M:Register(TYPE, "Blizz Stone",   PATH.."BlizzStone")
M:Register(TYPE, "Blizz Stone 2", PATH.."BlizzStone2")
M:Register(TYPE, "Diablo",        PATH.."Diablo") -- from rDiabloPlates2
M:Register(TYPE, "Diablo Darker", PATH.."DiabloMuted")
M:Register(TYPE, "dsm1",          PATH.."dsm1")
M:Register(TYPE, "dsm2",          PATH.."dsm2")
M:Register(TYPE, "dsm5",          PATH.."dsm5")
M:Register(TYPE, "dsm7",          PATH.."dsm7")
M:Register(TYPE, "dsm8",          PATH.."dsm8")
M:Register(TYPE, "dsm9",          PATH.."dsm9")
M:Register(TYPE, "dsm9b",         PATH.."dsm9b")
M:Register(TYPE, "DukeF",         PATH.."DukeF")
M:Register(TYPE, "Empty",         PATH.."Empty")
M:Register(TYPE, "Fade1",         PATH.."Fade1")
M:Register(TYPE, "Fade2",         PATH.."Fade2")
M:Register(TYPE, "Flat",          PATH.."Flat")
--M:Register(TYPE, "Frost",         PATH.."Frost")
M:Register(TYPE, "Glass1",        PATH.."Glass1")
M:Register(TYPE, "Glass2",        PATH.."Glass2")
--M:Register(TYPE, "Glaze",         PATH.."Glaze")
M:Register(TYPE, "Gloss",         PATH.."Gloss")
--M:Register(TYPE, "Graphite",      PATH.."Graphite")
--M:Register(TYPE, "GW2",           PATH.."cbar1bar") -- from ButgerStijl UI
--M:Register(TYPE, "GW2 Back",      PATH.."cbarBack") -- from ButgerStijl UI
M:Register(TYPE, "HalA",          PATH.."HalA")
M:Register(TYPE, "HalB",          PATH.."HalB")
M:Register(TYPE, "HalC",          PATH.."HalC")
M:Register(TYPE, "HalD",          PATH.."HalD")
M:Register(TYPE, "HalE",          PATH.."HalE")
M:Register(TYPE, "HalF",          PATH.."HalF")
M:Register(TYPE, "HalG",          PATH.."HalG")
M:Register(TYPE, "HalH",          PATH.."HalH")
M:Register(TYPE, "HalI",          PATH.."HalI")
M:Register(TYPE, "HalJ",          PATH.."HalJ")
M:Register(TYPE, "HalK",          PATH.."HalK")
M:Register(TYPE, "HalM",          PATH.."HalM")
M:Register(TYPE, "HalN",          PATH.."HalN")
M:Register(TYPE, "HalO",          PATH.."HalO")
M:Register(TYPE, "HalQ",          PATH.."HalQ")
M:Register(TYPE, "HalR",          PATH.."HalR")
M:Register(TYPE, "HalS",          PATH.."HalS")
M:Register(TYPE, "HalT",          PATH.."HalT")
M:Register(TYPE, "HalU",          PATH.."HalU")
M:Register(TYPE, "HalV",          PATH.."HalV")
M:Register(TYPE, "Healbot",       PATH.."Healbot")
M:Register(TYPE, "Lyn",           PATH.."Lyn1")
M:Register(TYPE, "Minimalist",    PATH.."Minimalist")
M:Register(TYPE, "MirageA",       PATH.."MirageA")
M:Register(TYPE, "MirageE",       PATH.."MirageE")
M:Register(TYPE, "Neal",          PATH.."Neal") -- from Roth UI
M:Register(TYPE, "Qulight",       PATH.."statusbar4") -- from oUF Qulight
--M:Register(TYPE, "Rocks",         PATH.."Rocks")
M:Register(TYPE, "Roth1",         PATH.."Roth1")
M:Register(TYPE, "Roth2",         PATH.."Roth2")
M:Register(TYPE, "Roth3",         PATH.."Roth3")
M:Register(TYPE, "Roth4",         PATH.."Roth4")
M:Register(TYPE, "Ruben",         PATH.."Ruben")
--M:Register(TYPE, "Runes",         PATH.."Runes")
M:Register(TYPE, "Savant1",       PATH.."Savant1")
--M:Register(TYPE, "Savant2",       PATH.."Savant2") -- blue
M:Register(TYPE, "Smooth1",       PATH.."Smooth1")
M:Register(TYPE, "Smooth2",       PATH.."Smooth2")
M:Register(TYPE, "Solid",         PATH.."Solid")
M:Register(TYPE, "Stone 1",       PATH.."Stone")
M:Register(TYPE, "Stone 2",       PATH.."StoneLighter2")
--M:Register(TYPE, "Striped",       PATH.."Striped")
M:Register(TYPE, "tap1",          PATH.."tap1")
M:Register(TYPE, "tap2",          PATH.."tap2")
M:Register(TYPE, "tap3",          PATH.."tap3")
M:Register(TYPE, "tap4",          PATH.."tap4")
M:Register(TYPE, "Tukz",          PATH.."Tukz")
